---
driver:
  name: vagrant

provisioner:
  name: chef_zero

platforms:
  - name: ubuntu-12.04

suites:
  -
    name: graphite_api
    run_list:
      - recipe[graphite-api]
    attributes:
      graphite_api:
        allowed_origins:
          - test.test.com
